### ISSUE TITLE
Official PSR-11 support in bernard

### ISSUE THREAD

**Issue by sagikazarmark** [ideationnet/bernard-container-router#1]
FYI Bernard has an official ContainerRouter for PSR-11.

**Comment by darrenmothersele** [comment]
Great! looks like that's a recent thing? https://github.com/bernardphp/bernard/issues/365

I'll mark this as deprecated.

**Comment by sagikazarmark** [comment]
Yes, and actually in the meantime the whole router concept changed: the container router disappeared, it became a receiver resolver.
